name: ldm-ckpt-conversion
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - pytorch-cuda=11.8
  - pip:
    - diffusers
    - transformers
    - omegaconf
    - safetensors
    - huggingface_hub 
